/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardValidateRouteImport } from './routes/dashboard.validate'
import { Route as DashboardReviewRouteImport } from './routes/dashboard.review'
import { Route as DashboardLearnRouteImport } from './routes/dashboard.learn'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard.history'
import { Route as DashboardCertificationRouteImport } from './routes/dashboard.certification'
import { Route as DashboardBatchPlannerRouteImport } from './routes/dashboard.batch-planner'
import { Route as DashboardReviewCertIdRouteImport } from './routes/dashboard.review.$certId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardValidateRoute = DashboardValidateRouteImport.update({
  id: '/validate',
  path: '/validate',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReviewRoute = DashboardReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLearnRoute = DashboardLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCertificationRoute = DashboardCertificationRouteImport.update({
  id: '/certification',
  path: '/certification',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBatchPlannerRoute = DashboardBatchPlannerRouteImport.update({
  id: '/batch-planner',
  path: '/batch-planner',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReviewCertIdRoute = DashboardReviewCertIdRouteImport.update({
  id: '/$certId',
  path: '/$certId',
  getParentRoute: () => DashboardReviewRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/batch-planner': typeof DashboardBatchPlannerRoute
  '/dashboard/certification': typeof DashboardCertificationRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/learn': typeof DashboardLearnRoute
  '/dashboard/review': typeof DashboardReviewRouteWithChildren
  '/dashboard/validate': typeof DashboardValidateRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/review/$certId': typeof DashboardReviewCertIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/batch-planner': typeof DashboardBatchPlannerRoute
  '/dashboard/certification': typeof DashboardCertificationRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/learn': typeof DashboardLearnRoute
  '/dashboard/review': typeof DashboardReviewRouteWithChildren
  '/dashboard/validate': typeof DashboardValidateRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/review/$certId': typeof DashboardReviewCertIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/batch-planner': typeof DashboardBatchPlannerRoute
  '/dashboard/certification': typeof DashboardCertificationRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/learn': typeof DashboardLearnRoute
  '/dashboard/review': typeof DashboardReviewRouteWithChildren
  '/dashboard/validate': typeof DashboardValidateRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/review/$certId': typeof DashboardReviewCertIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/batch-planner'
    | '/dashboard/certification'
    | '/dashboard/history'
    | '/dashboard/learn'
    | '/dashboard/review'
    | '/dashboard/validate'
    | '/dashboard/'
    | '/dashboard/review/$certId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard/batch-planner'
    | '/dashboard/certification'
    | '/dashboard/history'
    | '/dashboard/learn'
    | '/dashboard/review'
    | '/dashboard/validate'
    | '/dashboard'
    | '/dashboard/review/$certId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/batch-planner'
    | '/dashboard/certification'
    | '/dashboard/history'
    | '/dashboard/learn'
    | '/dashboard/review'
    | '/dashboard/validate'
    | '/dashboard/'
    | '/dashboard/review/$certId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/validate': {
      id: '/dashboard/validate'
      path: '/validate'
      fullPath: '/dashboard/validate'
      preLoaderRoute: typeof DashboardValidateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/review': {
      id: '/dashboard/review'
      path: '/review'
      fullPath: '/dashboard/review'
      preLoaderRoute: typeof DashboardReviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/learn': {
      id: '/dashboard/learn'
      path: '/learn'
      fullPath: '/dashboard/learn'
      preLoaderRoute: typeof DashboardLearnRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/certification': {
      id: '/dashboard/certification'
      path: '/certification'
      fullPath: '/dashboard/certification'
      preLoaderRoute: typeof DashboardCertificationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/batch-planner': {
      id: '/dashboard/batch-planner'
      path: '/batch-planner'
      fullPath: '/dashboard/batch-planner'
      preLoaderRoute: typeof DashboardBatchPlannerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/review/$certId': {
      id: '/dashboard/review/$certId'
      path: '/$certId'
      fullPath: '/dashboard/review/$certId'
      preLoaderRoute: typeof DashboardReviewCertIdRouteImport
      parentRoute: typeof DashboardReviewRoute
    }
  }
}

interface DashboardReviewRouteChildren {
  DashboardReviewCertIdRoute: typeof DashboardReviewCertIdRoute
}

const DashboardReviewRouteChildren: DashboardReviewRouteChildren = {
  DashboardReviewCertIdRoute: DashboardReviewCertIdRoute,
}

const DashboardReviewRouteWithChildren = DashboardReviewRoute._addFileChildren(
  DashboardReviewRouteChildren,
)

interface DashboardRouteChildren {
  DashboardBatchPlannerRoute: typeof DashboardBatchPlannerRoute
  DashboardCertificationRoute: typeof DashboardCertificationRoute
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardLearnRoute: typeof DashboardLearnRoute
  DashboardReviewRoute: typeof DashboardReviewRouteWithChildren
  DashboardValidateRoute: typeof DashboardValidateRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBatchPlannerRoute: DashboardBatchPlannerRoute,
  DashboardCertificationRoute: DashboardCertificationRoute,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardLearnRoute: DashboardLearnRoute,
  DashboardReviewRoute: DashboardReviewRouteWithChildren,
  DashboardValidateRoute: DashboardValidateRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
